### ISSUE TITLE
@bem-react/classname: classnames stopped working @1.2.0

### ISSUE THREAD

**Issue by roxkisrover** [bem/bem-react#371]
```js
import { classnames } from '@bem-react/classname';
classnames('Block', 'Mix', undefined, 'Block');
```
Even this code from the docs throws an error: ```TypeError: Object(...) is not a function``` after upgrading to v1.2.0. Worked fine at v 1.1.1. 🤷‍♂️

**Comment by belozer** [comment]
@roxkisrover you need use another package `import { classnames } from '@bem-react/classnames';`
